apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy-green
  labels:
    app: capstone
    version: green
spec:
  selector:
    matchLabels:
      app: capstone
      version: green
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: capstone
        version: green
    spec:
      containers:
      - name: capstone
        image: leoadams/capstone:e2d53f32e7116208f55f76658328f59d51c5299a
        imagePullPolicy: Always
        ports:
          - containerPort: 80