apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy-v1
  labels:
    app: capstone
    version: v1
spec:
  selector:
    matchLabels:
      app: capstone
      version: v1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: capstone
        version: v1
    spec:
      containers:
      - name: capstone
        image: leoadams/capstone:v1
        #imagePullPolicy: Always
        ports:
          - containerPort: 80
