apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy
  labels:
    app: capstone
    version: blue
spec:
  selector:
    matchLabels:
      app: capstone
      version: blue
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: capstone
        version: blue
    spec:
      containers:
      - name: capstone
        image: leoadams/capstone:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
