apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
    version: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
